/* Generated By:JavaCC: Do not edit this line. LsysParserConstants.java */
package drawing.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LsysParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CHANGECOLOR = 6;
  /** RegularExpression Id. */
  int MARK = 7;
  /** RegularExpression Id. */
  int LABEL = 8;
  /** RegularExpression Id. */
  int PUSH = 9;
  /** RegularExpression Id. */
  int POP = 10;
  /** RegularExpression Id. */
  int COMMA = 11;
  /** RegularExpression Id. */
  int WIDTHINCR = 12;
  /** RegularExpression Id. */
  int WIDTHDECR = 13;
  /** RegularExpression Id. */
  int DOUBLELENGTH = 14;
  /** RegularExpression Id. */
  int HALFLENGTH = 15;
  /** RegularExpression Id. */
  int EQUAL = 16;
  /** RegularExpression Id. */
  int RIGHT = 17;
  /** RegularExpression Id. */
  int LEFT = 18;
  /** RegularExpression Id. */
  int HRIGHT = 19;
  /** RegularExpression Id. */
  int HLEFT = 20;
  /** RegularExpression Id. */
  int STRING_LITERAL = 21;
  /** RegularExpression Id. */
  int IDENTIFIER = 22;
  /** RegularExpression Id. */
  int LETTER = 23;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"*\"",
    "\"@\"",
    "\"|\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\"\\\'\"",
    "\"\\\"\"",
    "\"~\"",
    "\"`\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"$\"",
    "\"%\"",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
  };

}
